
Remove-Alias "[" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "b2sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "b3sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "base32" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "base64" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "basename" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "basenc" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "cat" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "cksum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "comm" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "cp" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "csplit" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "cut" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "date" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "dd" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "df" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "dir" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "dircolors" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "dirname" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "du" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "echo" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "env" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "expand" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "expr" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "factor" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "false" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "fmt" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "fold" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "hashsum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "head" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "join" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "link" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "ln" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "ls" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "md5sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "mkdir" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "mktemp" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "more" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "mv" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "nl" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "numfmt" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "od" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "paste" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "pr" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "printenv" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "printf" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "ptx" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "pwd" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "readlink" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "realpath" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "rm" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "rmdir" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "seq" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sha1sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sha224sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sha256sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sha3-224sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sha3-256sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sha3-384sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sha3-512sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sha384sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sha3sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sha512sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "shake128sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "shake256sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "shred" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "shuf" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sleep" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sort" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "split" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "sum" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "tac" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "tail" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "tee" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "test" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "touch" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "tr" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "true" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "truncate" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "tsort" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "unexpand" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "uniq" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "unlink" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "vdir" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "wc" -Force -ErrorAction SilentlyContinue -Scope Global 
Remove-Alias "yes" -Force -ErrorAction SilentlyContinue -Scope Global 

